# Generated by Django 4.2.7 on 2024-02-16 13:49

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_description', tinymce.models.HTMLField()),
                ('news_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='news_title')),
            ],
        ),
    ]
