# Generated by Django 4.2.7 on 2024-02-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhiring',
            old_name='name',
            new_name='jobTitle',
        ),
    ]
