# Generated by Django 4.2.7 on 2024-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('s_class', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Student Entry',
            },
        ),
    ]
