# Generated by Django 4.2.7 on 2024-02-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_entry',
            options={'verbose_name_plural': 'Student Entry'},
        ),
    ]
