# Generated by Django 4.2.7 on 2024-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapp', '0004_alter_student_entry_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_entry',
            name='fname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_entry',
            name='lname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_entry',
            name='s_class',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_entry',
            name='subject',
            field=models.TextField(max_length=50),
        ),
    ]
