# Generated by Django 4.2.7 on 2024-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDapp', '0005_alter_student_entry_fname_alter_student_entry_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_entry',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
